# flake8: noqa E501

from pytmdb.search import SearchCollection
from pytmdb.search import SearchMovie
from pytmdb.search import SearchPerson

search_person_expected = [
    (
        "hugh jackman",
        [
            SearchPerson(
                adult=False,
                gender=2,
                id=6968,
                known_for_department="Acting",
                name="Hugh Jackman",
                original_name="Hugh Jackman",
                popularity=23.511,
                profile_path="/4Xujtewxqt6aU0Y81tsS9gkjizk.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/9X7YweCJw3q8Mcf6GadxReFEksM.jpg",
                        genre_ids=[28, 18, 878],
                        id=263115,
                        original_language="en",
                        original_title="Logan",
                        overview="In the near future, a weary Logan cares for an ailing Professor X in a hideout on the Mexican border. But Logan's attempts to hide from the world and his legacy are upended when a young mutant arrives, pursued by dark forces.",
                        popularity=50.098,
                        poster_path="/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
                        release_date="2017-02-28",
                        title="Logan",
                        video=False,
                        vote_average=7.818,
                        vote_count=17959,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/6RZZNx2irPBou7JyFGwOIoioPYK.jpg",
                        genre_ids=[28, 12, 878],
                        id=127585,
                        original_language="en",
                        original_title="X-Men: Days of Future Past",
                        overview="The ultimate X-Men ensemble fights a war for the survival of the species across two time periods as they join forces with their younger selves in an epic battle that must change the past – to save our future.",
                        popularity=47.437,
                        poster_path="/tYfijzolzgoMOtegh1Y7j2Enorg.jpg",
                        release_date="2014-05-15",
                        title="X-Men: Days of Future Past",
                        video=False,
                        vote_average=7.5,
                        vote_count=14309,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/oWKcexbupmmdUEtU8h0WK1DUWmt.jpg",
                        genre_ids=[18, 53, 80],
                        id=146233,
                        original_language="en",
                        original_title="Prisoners",
                        overview="Keller Dover faces a parent's worst nightmare when his 6-year-old daughter, Anna, and her friend go missing. The only lead is an old motorhome that had been parked on their street. The head of the investigation, Detective Loki, arrests the driver, but a lack of evidence forces Loki to release his only suspect. Dover, knowing that his daughter's life is at stake, decides that he has no choice but to take matters into his own hands.",
                        popularity=47.471,
                        poster_path="/tuZhZ6biFMr5n9YSVuHOJnNL1uU.jpg",
                        release_date="2013-09-18",
                        title="Prisoners",
                        video=False,
                        vote_average=8.089,
                        vote_count=10577,
                    ),
                ],
            )
        ],
    ),
    (
        "jack ni",
        [
            SearchPerson(
                adult=False,
                gender=2,
                id=514,
                known_for_department="Acting",
                name="Jack Nicholson",
                original_name="Jack Nicholson",
                popularity=16.414,
                profile_path="/hBHcQIEa6P48HQAlLZkh0eKSSkG.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/mmd1HnuvAzFc4iuVJcnBrhDNEKr.jpg",
                        genre_ids=[27, 53],
                        id=694,
                        original_language="en",
                        original_title="The Shining",
                        overview="Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, along with his wife Wendy and their son Danny, must live isolated from the rest of the world for the winter. But they aren't prepared for the madness that lurks within.",
                        popularity=40.978,
                        poster_path="/nRj5511mZdTl4saWEPoj9QroTIu.jpg",
                        release_date="1980-05-23",
                        title="The Shining",
                        video=False,
                        vote_average=8.221,
                        vote_count=15998,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/6WRrGYalXXveItfpnipYdayFkQB.jpg",
                        genre_ids=[18, 53, 80],
                        id=1422,
                        original_language="en",
                        original_title="The Departed",
                        overview="To take down South Boston's Irish Mafia, the police send in one of their own to infiltrate the underworld, not realizing the syndicate has done likewise. While an undercover cop curries favor with the mob kingpin, a career criminal rises through the police ranks. But both sides soon discover there's a mole among them.",
                        popularity=41.242,
                        poster_path="/nT97ifVT2J1yMQmeq20Qblg61T.jpg",
                        release_date="2006-10-04",
                        title="The Departed",
                        video=False,
                        vote_average=8.167,
                        vote_count=13634,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/qUq3QTr2KLvGIcN0GaaaYx9bbyH.jpg",
                        genre_ids=[18],
                        id=510,
                        original_language="en",
                        original_title="One Flew Over the Cuckoo's Nest",
                        overview="A petty criminal fakes insanity to serve his sentence in a mental ward rather than prison. He soon finds himself as a leader to the other patients—and an enemy to the cruel, domineering nurse who runs the ward.",
                        popularity=33.653,
                        poster_path="/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg",
                        release_date="1975-11-19",
                        title="One Flew Over the Cuckoo's Nest",
                        video=False,
                        vote_average=8.421,
                        vote_count=9524,
                    ),
                ],
            ),
            SearchPerson(
                adult=False,
                gender=2,
                id=7066,
                known_for_department="Sound",
                name="Jack Nitzsche",
                original_name="Jack Nitzsche",
                popularity=1.4,
                profile_path="/7j4DfC2JLPdInoNUbVHthNYoSpm.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/qUq3QTr2KLvGIcN0GaaaYx9bbyH.jpg",
                        genre_ids=[18],
                        id=510,
                        original_language="en",
                        original_title="One Flew Over the Cuckoo's Nest",
                        overview="A petty criminal fakes insanity to serve his sentence in a mental ward rather than prison. He soon finds himself as a leader to the other patients—and an enemy to the cruel, domineering nurse who runs the ward.",
                        popularity=33.653,
                        poster_path="/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg",
                        release_date="1975-11-19",
                        title="One Flew Over the Cuckoo's Nest",
                        video=False,
                        vote_average=8.421,
                        vote_count=9524,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/lNlWuDxf3EvnbpNCMc7zVtpEQAC.jpg",
                        genre_ids=[27],
                        id=9552,
                        original_language="en",
                        original_title="The Exorcist",
                        overview="12-year-old Regan MacNeil begins to adapt an explicit new personality as strange events befall the local area of Georgetown. Her mother becomes torn between science and superstition in a desperate bid to save her daughter, and ultimately turns to her last hope: Father Damien Karras, a troubled priest who is struggling with his own faith.",
                        popularity=63.726,
                        poster_path="/4ucLGcXVVSVnsfkGtbLY4XAius8.jpg",
                        release_date="1973-12-26",
                        title="The Exorcist",
                        video=False,
                        vote_average=7.717,
                        vote_count=7096,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/yjGllQUm28R4X9xD9T5xMszirgw.jpg",
                        genre_ids=[80, 18],
                        id=235,
                        original_language="en",
                        original_title="Stand by Me",
                        overview="Gordie, Chris, Teddy and Vern are four friends who decide to hike to find the corpse of Ray Brower, a local teenager, who was hit by a train while plucking blueberries in the wild.",
                        popularity=20.373,
                        poster_path="/vz0w9BSehcqjDcJOjRaCk7fgJe7.jpg",
                        release_date="1986-08-08",
                        title="Stand by Me",
                        video=False,
                        vote_average=7.862,
                        vote_count=5210,
                    ),
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=74977,
                known_for_department="Sound",
                name="Jack M. Nietzsche Jr.",
                original_name="Jack M. Nietzsche Jr.",
                popularity=1.4,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/bZbBTrefbgTvVK8CN56zKIHNomI.jpg",
                        genre_ids=[16, 10751, 14],
                        id=10144,
                        original_language="en",
                        original_title="The Little Mermaid",
                        overview="This colorful adventure tells the story of an impetuous mermaid princess named Ariel who falls in love with the very human Prince Eric and puts everything on the line for the chance to be with him. Memorable songs and characters -- including the villainous sea witch Ursula.",
                        popularity=104.294,
                        poster_path="/plcZXvI310FkbwIptvd6rqk63LP.jpg",
                        release_date="1989-11-17",
                        title="The Little Mermaid",
                        video=False,
                        vote_average=7.353,
                        vote_count=7219,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/8uNx4YtClqB9duM4n6jOx8vWvvl.jpg",
                        genre_ids=[35, 10749, 18],
                        id=4964,
                        original_language="en",
                        original_title="Knocked Up",
                        overview="A slacker and a career-driven woman accidentally conceive a child after a one-night stand. As they try to make the relationship work, they must navigate the challenges of parenthood and their differences in lifestyle and maturity.",
                        popularity=17.474,
                        poster_path="/b4OaXw2MW97VvIiZE0Sbn1NfxSh.jpg",
                        release_date="2007-06-01",
                        title="Knocked Up",
                        video=False,
                        vote_average=6.268,
                        vote_count=3620,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/qhwmkPBg9MithppIXhUNVCYA4uR.jpg",
                        genre_ids=[12, 35, 10751, 878],
                        id=11158,
                        original_language="en",
                        original_title="Honey, I Blew Up the Kid",
                        overview="Wayne Szalinski is at it again. But instead of shrinking things, he tries to make a machine that can make things grow. As in the first one, his machine isn't quite accurate. But when he brings Nick & his toddler son Adam to see his invention, the machine unexpectedly starts working. And when Adam comes right up to the machine, he gets zapped along with his stuffed bunny.",
                        popularity=10.499,
                        poster_path="/iLWZJAIcSqthsmJ3pMbtiE9Ap6N.jpg",
                        release_date="1992-07-16",
                        title="Honey, I Blew Up the Kid",
                        video=False,
                        vote_average=5.218,
                        vote_count=1051,
                    ),
                ],
            ),
            SearchPerson(
                adult=False,
                gender=2,
                id=1246939,
                known_for_department="Acting",
                name="Jack Nicklaus",
                original_name="Jack Nicklaus",
                popularity=1.38,
                profile_path="/jRXj49nWVcEWIzgsRAYRDWT78z9.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[99],
                        id=489562,
                        original_language="en",
                        original_title="Back Nine at Cherry Hills: The Legends of the 1960 U.S. Open",
                        overview="At the 1960 U.S. Open, aging legend Ben Hogan dueled talented amateur Jack Nicklaus and emerging superstar Arnold Palmer play in an exciting final round clash to determine the 1960 U.S Open Champion.. This documentary chronicles  a seminal event in golf that represented the changing of the guard as the three battled to the wire for golf supremacy of the era.",
                        popularity=1.4,
                        poster_path="/yplY6MXk7q1EAekTa8KUc4yUSha.jpg",
                        release_date="2008-06-11",
                        title="Back Nine at Cherry Hills: The Legends of the 1960 U.S. Open",
                        video=False,
                        vote_average=6.0,
                        vote_count=1,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/3faTSDiumSVm5FOFeaZAene3hrk.jpg",
                        genre_ids=[],
                        id=138229,
                        original_language="en",
                        original_title=None,
                        overview="Tiger Woods reveals the unique story of his astonishing life in golf. From the promise of a child prodigy to its fulfillment in the most dominant force in the history of sport. This series chronicles a story of unparalleled ambition, dedication and success woven with personal interviews and previously unseen photographs, film and video archives. Narrated by Laurence Fishburne, Tiger gives a exclusive account of his quest for golf's highest honours. Tiger offers a fascinating insight into what it takes to be the very best. It's a rare opportunity to share the thoughts, feel the pressures, understand the anxieties and savour the thrills of one of the most influential athletes of all time.",
                        popularity=1.96,
                        poster_path="/AkOkkrcDhgaLgfSwKH8fsVwMtH1.jpg",
                        release_date=None,
                        title=None,
                        video=None,
                        vote_average=9.0,
                        vote_count=1,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[],
                        id=62240,
                        original_language="en",
                        original_title="Jack Nicklaus Golf My Way",
                        overview="Jack Nicklaus' insights and instruction broken down through playing lessons that focus on various aspects of the game and appeal to golfers of all skill levels. The footage, much of which was filmed 25 years ago in the midst of Nicklaus' record-setting career",
                        popularity=0.6,
                        poster_path=None,
                        release_date="2008-02-17",
                        title="Jack Nicklaus Golf My Way",
                        video=False,
                        vote_average=0.0,
                        vote_count=0,
                    ),
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=2870382,
                known_for_department="Acting",
                name="Jack Niccol",
                original_name="Jack Niccol",
                popularity=0.75,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/oTOKHnJRNmZh4JtuE5GJ2tFVpWW.jpg",
                        genre_ids=[80, 18, 53],
                        id=1830,
                        original_language="en",
                        original_title="Lord of War",
                        overview="Yuri Orlov is a globetrotting arms dealer and, through some of the deadliest war zones, he struggles to stay one step ahead of a relentless Interpol agent, his business rivals and even some of his customers who include many of the world's most notorious dictators. Finally, he must also face his own conscience.",
                        popularity=24.384,
                        poster_path="/3MGQD4yXokufNlW1AyRXdiy7ytP.jpg",
                        release_date="2005-09-16",
                        title="Lord of War",
                        video=False,
                        vote_average=7.277,
                        vote_count=4193,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=1,
                id=1537676,
                known_for_department="Production",
                name="Nina Jack",
                original_name="Nina Jack",
                popularity=1.188,
                profile_path="/cMqupP12hfmjAeqkQZzq2NADrcc.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/hPea3Qy5Gd6z4kJLUruBbwAH8Rm.jpg",
                        genre_ids=[80, 18],
                        id=60059,
                        original_language="en",
                        original_title=None,
                        overview='Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
                        popularity=169.484,
                        poster_path="/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg",
                        release_date=None,
                        title=None,
                        video=None,
                        vote_average=8.636,
                        vote_count=4225,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/A5lVyejMsP5G7rAJBwU9ug3Wzou.jpg",
                        genre_ids=[18],
                        id=1104,
                        original_language="en",
                        original_title=None,
                        overview="Set in 1960-1970 New York, this sexy, stylized and provocative drama follows the lives of the ruthlessly competitive men and women of Madison Avenue advertising.",
                        popularity=152.747,
                        poster_path="/5jOedTeytYzlJZwU66MFjmLHhHX.jpg",
                        release_date=None,
                        title=None,
                        video=None,
                        vote_average=8.103,
                        vote_count=999,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/qQnIdQhRA9VO8X8lF5Jo6ZwE9AN.jpg",
                        genre_ids=[35, 18],
                        id=99652,
                        original_language="en",
                        original_title=None,
                        overview="Explore the secret life of a woman we all grew up watching: the sitcom wife. The series looks to break television convention and ask what the world looks like through her eyes. Alternating between single-camera realism and multi-camera zaniness, the formats will inform one another as we imagine what happens when the sitcom wife escapes her confines, and takes the lead in her own life.",
                        popularity=8.613,
                        poster_path="/mXB18fB9nBWHZdi9AdOpsHmSKVL.jpg",
                        release_date=None,
                        title=None,
                        video=None,
                        vote_average=6.884,
                        vote_count=56,
                    ),
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=1385755,
                known_for_department="Acting",
                name="Jack Niedenthal",
                original_name="Jack Niedenthal",
                popularity=0.6,
                profile_path=None,
                known_for=[],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=2412929,
                known_for_department="Production",
                name="Jack Nielsen",
                original_name="Jack Nielsen",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/14ATSJsT3KDmHQdZY8FeEMxfPoG.jpg",
                        genre_ids=[18],
                        id=631880,
                        original_language="en",
                        original_title="Tyger Tyger",
                        overview="A woman and her group of selfless thieves rob a pharmacy and hit the road to distribute medication, but find themselves trapped in the fringe lands of a law-less psychedelic city.",
                        popularity=4.347,
                        poster_path="/5fhlV6jdEd9iqYnE9XUQAAhvw82.jpg",
                        release_date="2021-02-26",
                        title="Tyger Tyger",
                        video=False,
                        vote_average=6.6,
                        vote_count=7,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=2,
                id=89488,
                known_for_department="Acting",
                name="Jack Nillson",
                original_name="Jack Nillson",
                popularity=0.6,
                profile_path="/qEUZrDy9THtA1wyroAWnZLw0tvi.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[],
                        id=17517,
                        original_language="en",
                        original_title="UFC 13: The Ultimate Force",
                        overview="UFC 13: Ultimate Force was a mixed martial arts event held by the Ultimate Fighting Championship on May 30, 1997 in Augusta, Georgia. The event was seen live on pay per view in the United States, and later released on home video.",
                        popularity=3.396,
                        poster_path="/5bbmGV4TwLTV2LIWipodXpvnd3G.jpg",
                        release_date="1997-05-30",
                        title="UFC 13: The Ultimate Force",
                        video=True,
                        vote_average=7.0,
                        vote_count=6,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=2,
                id=1328230,
                known_for_department="Directing",
                name="Jack Niedenthal",
                original_name="Jack Niedenthal",
                popularity=0.6,
                profile_path="/gOT0spc30erZLUUg6oAgHJzh8XX.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[18, 10751, 9648],
                        id=274489,
                        original_language="mh",
                        original_title="Ainikien jidjid ilo boñ",
                        overview="An elderly nuclear survivor from Bikini Atoll in the Pacific summons a mysterious ancient deity to help reunite his family.",
                        popularity=0.6,
                        poster_path=None,
                        release_date="2012-09-14",
                        title="The Sound of Crickets at Night",
                        video=False,
                        vote_average=5.3,
                        vote_count=3,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[27, 14, 18],
                        id=392069,
                        original_language="en",
                        original_title="Lañinbwil's Gift",
                        overview="Laninbwil's Gift is the story of Jacob, an old island man with a complicated secret. When Jacob was a teenager, a noniep, a Marshallese fairy known for helping troubled souls, transformed him from a simpleton into a normal young man. This favor, however, came with a cost: The noniep made Jacob promise that one day he must bestow this new-found intelligence upon another deserving person. After a lifetime of pondering this otherworldly commitment to the noniep, Jacob discovers Laninbwil, a homeless young man. Just when Jacob begins to get close to the troubled youth, Laninbwil unwittingly gets caught up in a war of mystical power between an evil Mejenkwar, a demon that possesses pregnant women, and her archenemy, the gifted, shamanic old woman, Lijimu.",
                        popularity=0.6,
                        poster_path=None,
                        release_date="2012-05-01",
                        title="Lañinbwil's Gift",
                        video=False,
                        vote_average=4.5,
                        vote_count=1,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[18, 10751],
                        id=276619,
                        original_language="mh",
                        original_title="Zori",
                        overview='A young Marshallese boy, Labro, wakes up one morning anxious for his grandmother to fulfill her promise of buying him ice cream. She agrees, but demands that he do some work first, commanding him -- with a sweep of her arm -- to "clean up all the garbage everywhere." As Labro goes out the door of his rustic shack, he realizes that one of his zoris is missing. His grandmother, angry because he has yet again lost one of his flip flops, gives him an ultimatum: "Do not come back to the house until you have zoris on both of your feet." So Labro begins his quest under the hot island sun to clean up \'everywhere\' and to find his other zori...',
                        popularity=0.6,
                        poster_path=None,
                        release_date="2013-09-29",
                        title="Zori",
                        video=False,
                        vote_average=0.0,
                        vote_count=0,
                    ),
                ],
            ),
            SearchPerson(
                adult=False,
                gender=2,
                id=2945042,
                known_for_department="Directing",
                name="Jack Nicoletti",
                original_name="Jack Nicoletti",
                popularity=0.6,
                profile_path="/v7rfKbvMWGOh5xn70MzWfOXPZlT.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/cbAoDAE4zv5PdHOBwH0fsrmVKmN.jpg",
                        genre_ids=[80, 35],
                        id=788186,
                        original_language="en",
                        original_title="The Middle Men",
                        overview="Two newly hired video store clerks are asked by their new boss to deliver a package to a theater across town. Unbeknownst to them, the package is truly a shipment of cocaine for a local drug kingpin.",
                        popularity=0.6,
                        poster_path="/nft1W86mueRax9MkVkrXxv0hLuK.jpg",
                        release_date="2021-02-19",
                        title="The Middle Men",
                        video=False,
                        vote_average=0.0,
                        vote_count=0,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[18, 10749],
                        id=865183,
                        original_language="en",
                        original_title="Midnight Train",
                        overview="A young man reminisces on his relationship with a friend while awaiting a midnight train to New York City.",
                        popularity=0.6,
                        poster_path="/kluWI6wBTQWdSeWafTzLKcMkQmJ.jpg",
                        release_date="",
                        title="Midnight Train",
                        video=False,
                        vote_average=0.0,
                        vote_count=0,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[35, 80],
                        id=881270,
                        original_language="en",
                        original_title="Doing the Dishes at Marcy Playground",
                        overview="Three stoned college students are thrown into an awkward situation when a police officer catches them smoking in their local playground.",
                        popularity=0.6,
                        poster_path="/dklSxr7Hh5afH4vEfw65MbX6j2B.jpg",
                        release_date="2021-10-08",
                        title="Doing the Dishes at Marcy Playground",
                        video=False,
                        vote_average=0.0,
                        vote_count=0,
                    ),
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=3195423,
                known_for_department="Acting",
                name="Jack Nichols",
                original_name="Jack Nichols",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/zMDfSDW6n5dyoVdZA9Bswc7aRy0.jpg",
                        genre_ids=[99],
                        id=661271,
                        original_language="en",
                        original_title="The Homosexuals",
                        overview="On March 7, 1967, 40 million Americans tuned in to watch CBS Reports: The Homosexuals, network television’s first documentary on homosexuality. Near the top of the program, host and interviewer Mike Wallace calls homosexuals “the most despised minority in the United States.” The hour that follows is filled with salacious location footage, sermonizing therapists, and shadowed interviews with distraught homosexuals.",
                        popularity=0.657,
                        poster_path="/8mXqEAxMg5paZWVmvGsBNZw8Faf.jpg",
                        release_date="1967-03-07",
                        title="The Homosexuals",
                        video=False,
                        vote_average=1.0,
                        vote_count=1,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=3943835,
                known_for_department="Production",
                name="Jack Nikolaidis",
                original_name="Jack Nikolaidis",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/oXesrxVxymFwlzlcLGj4DjAhlUb.jpg",
                        genre_ids=[80, 18],
                        id=94372,
                        original_language="en",
                        original_title=None,
                        overview="The Fugitive Task Force relentlessly tracks and captures the notorious criminals on the Bureau’s Most Wanted list. Seasoned agent Jess LaCroix oversees the highly skilled team that functions as a mobile undercover unit that is always out in the field, pursuing those who are most desperate to elude justice.",
                        popularity=81.156,
                        poster_path="/vpprgWCuDJ4CucJhFB4fBHdX9D7.jpg",
                        release_date=None,
                        title=None,
                        video=None,
                        vote_average=7.698,
                        vote_count=318,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=2,
                id=3262411,
                known_for_department="Acting",
                name="Jack Nielen",
                original_name="Jack Nielen",
                popularity=0.6,
                profile_path="/V8v5kmg0R5tPAwdE816kJqyG39.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/2nJJxHjBTDVDIbpHylCsDVQ3alG.jpg",
                        genre_ids=[18],
                        id=716612,
                        original_language="en",
                        original_title="Spencer",
                        overview="During her Christmas holidays with the royal family at the Sandringham estate in Norfolk, England, Diana decides to leave her marriage to Prince Charles.",
                        popularity=12.685,
                        poster_path="/7GcqdBKaMM9BWXWN07BirBMkcBF.jpg",
                        release_date="2021-11-04",
                        title="Spencer",
                        video=False,
                        vote_average=6.862,
                        vote_count=1445,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=3305361,
                known_for_department="Acting",
                name="Jack Nicholls",
                original_name="Jack Nicholls",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/kE0G21t1ktp7pe9QrIcWtEl05RK.jpg",
                        genre_ids=[18],
                        id=665901,
                        original_language="en",
                        original_title="Violet",
                        overview="Violet realizes that her entire life is built on fear-based decisions, and must do everything differently to become her true self.",
                        popularity=3.09,
                        poster_path="/h88HvuJGmbz6ABBFHoltN4Ratib.jpg",
                        release_date="2021-10-29",
                        title="Violet",
                        video=False,
                        vote_average=7.3,
                        vote_count=10,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=2088710,
                known_for_department="Acting",
                name="Jack Niebling",
                original_name="Jack Niebling",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[],
                        id=536906,
                        original_language="en",
                        original_title="Old Man of the Rooks",
                        overview='When an ancient evil descends on Rookery Farm, a newlywed couple find out what "til death do us part" really means when they are visited by the Old Man of the Rooks.',
                        popularity=0.6,
                        poster_path="/qVaK39fMbBJqV4LPt6fT75dHjlT.jpg",
                        release_date="2018-01-06",
                        title="Old Man of the Rooks",
                        video=False,
                        vote_average=0.0,
                        vote_count=0,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=2072179,
                known_for_department="Directing",
                name="Jack Nicol",
                original_name="Jack Nicol",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/f1UJO3aL1e7TSFPZFLfBjs3eEF3.jpg",
                        genre_ids=[99],
                        id=532102,
                        original_language="en",
                        original_title="She Shears",
                        overview="In the gruelling world of competitive sheep shearing there is no women's section. Women and men compete together. She Shears is the story of passion, purpose and determination and five women for whom shearing is not just a job.",
                        popularity=0.6,
                        poster_path="/6Pos1U4Cnn9K226zjyRcHNTYHPh.jpg",
                        release_date="2018-08-01",
                        title="She Shears",
                        video=False,
                        vote_average=0.0,
                        vote_count=0,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=2,
                id=2923667,
                known_for_department="Acting",
                name="Jack Nilson",
                original_name="Jack Nilson",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[],
                        id=17785,
                        original_language="en",
                        original_title="UFC 11.5",
                        overview='The Ultimate Ultimate 2 (also referred to as "Ultimate Ultimate 1996" and "UFC 11.5") was a mixed martial arts event held by the Ultimate Fighting Championship on December 7, 1996. The event took place at the Fair Park Arena in Birmingham, Alabama, and was broadcast live on pay-per-view in the United States, and released on home video.',
                        popularity=2.309,
                        poster_path="/1Pft9cQQKJlvSH1WPHYXBUZ6c5N.jpg",
                        release_date="1996-12-07",
                        title="UFC 11.5: Ultimate Ultimate 2",
                        video=True,
                        vote_average=6.8,
                        vote_count=8,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=2966413,
                known_for_department="Writing",
                name="Jack Nixon",
                original_name="Jack Nixon",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[],
                        id=793936,
                        original_language="en",
                        original_title="World at War",
                        overview="A fifteen-year old fisherman joins legendary conservationist Dr. Sylvia Earle on a global quest to make peace with nature and save a dying ocean.",
                        popularity=0.6,
                        poster_path=None,
                        release_date="",
                        title="World at War",
                        video=False,
                        vote_average=0.0,
                        vote_count=0,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=2298146,
                known_for_department="Acting",
                name="Jack Nisbet",
                original_name="Jack Nisbet",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/dAFKnTzyOBbZyRCAb33F632ctva.jpg",
                        genre_ids=[14, 18, 27, 10749],
                        id=10395,
                        original_language="en",
                        original_title="Wolf",
                        overview="Aging publisher Will Randall is at the end of his rope when a younger co-worker snatches his job out from under his nose. But after being bitten by a wolf, Will suddenly finds himself full of youthful vigor. As he struggles to regain his position, he becomes enthralled with Laura Alden, his former boss's daughter. And, as increasingly animal-like urges begin to overwhelm him, Randall worries that he may be turning into the creature that bit him.",
                        popularity=9.826,
                        poster_path="/8ocZb9x6rN82i8ZzZ05j1vWKVOC.jpg",
                        release_date="1994-06-17",
                        title="Wolf",
                        video=False,
                        vote_average=6.092,
                        vote_count=799,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=4079024,
                known_for_department="Editing",
                name="Jack Nicholls",
                original_name="Jack Nicholls",
                popularity=0.6,
                profile_path=None,
                known_for=[],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=1199799,
                known_for_department="Directing",
                name="Jack Nixon-Browne",
                original_name="Jack Nixon-Browne",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[],
                        id=339798,
                        original_language="en",
                        original_title="Dracula",
                        overview="This 1973 Canadian TV movie adaptation of  DRACULA played on CBC's Purple Playhouse program. Norman Welsh plays the vampire count that resembles Stoker's original vision for the character.",
                        popularity=0.87,
                        poster_path=None,
                        release_date="1973-01-01",
                        title="Dracula",
                        video=False,
                        vote_average=5.0,
                        vote_count=1,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[9648, 10770],
                        id=215096,
                        original_language="en",
                        original_title="Doctor Yes: The Hyannis Affair",
                        overview="A man falls for his nubile stepdaughter. When his hot wife founds out about this, she is furious. Murder ensues. It's obvious who's the guilty party. Or is it?",
                        popularity=1.391,
                        poster_path="/aJlHdkoiktTCJg64A5iMSfdXmLk.jpg",
                        release_date="1983-01-01",
                        title="Doctor Yes: The Hyannis Affair",
                        video=False,
                        vote_average=1.0,
                        vote_count=1,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[80, 18, 53, 10770],
                        id=1002126,
                        original_language="en",
                        original_title="When Angels Fly",
                        overview="When Marta Wendell's institutionalized sister suddenly dies, she suspects foul play. To uncover the truth she gets the job as chief surgical nurse at the hospital.",
                        popularity=0.6,
                        poster_path=None,
                        release_date="1983-06-01",
                        title="When Angels Fly",
                        video=False,
                        vote_average=0.0,
                        vote_count=0,
                    ),
                ],
            ),
            SearchPerson(
                adult=False,
                gender=2,
                id=2122952,
                known_for_department="Directing",
                name="Nicolas Jack Davies",
                original_name="Nicolas Jack Davies",
                popularity=0.6,
                profile_path="/lpAKPGuMJKU2WUlsTSdXCsyVYXT.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/fhtIp3Xbj0CJ9w2TsSEHuh8woOx.jpg",
                        genre_ids=[99, 10402],
                        id=545581,
                        original_language="en",
                        original_title="Rudeboy: The Story of Trojan Records",
                        overview="This stylish documentary about the iconic ska, reggae and rock-steady label is a timely and wide-ranging celebration of british Jamaican working-class youth culture.",
                        popularity=1.17,
                        poster_path="/gUgtbuZLxbG5YeHeYD8L6cVWNOv.jpg",
                        release_date="2018-10-12",
                        title="Rudeboy: The Story of Trojan Records",
                        video=False,
                        vote_average=6.7,
                        vote_count=15,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/pMycNh15Kr159I5YnrcA4EZ2Zzr.jpg",
                        genre_ids=[10402, 16],
                        id=894214,
                        original_language="en",
                        original_title="Gorillaz: Song Machine Live From Kong",
                        overview="The set features songs from the Song Machine project, along with some revered classics from the group’s back catalogue.  The full Gorillaz live band, plus a choice selection of featured artists, showcasing their first live performance since 2018.  This special presentation also features a pre-show programme and exclusive behind-the-scenes footage.",
                        popularity=2.416,
                        poster_path="/p0bez9RKa1yJdzsAhG0XLeeinET.jpg",
                        release_date="2021-12-08",
                        title="Gorillaz: Song Machine Live From Kong",
                        video=False,
                        vote_average=5.3,
                        vote_count=3,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/jhLeBhOB7hUjNvUnGcB3oH9ilZN.jpg",
                        genre_ids=[10402, 99],
                        id=147001,
                        original_language="en",
                        original_title="Mumford & Sons: The Road to Red Rocks",
                        overview="1. Lovers' Eyes 2. Little Lion Man 3. Below My Feet 4. Roll Away Your Stone 5. Lover Of The Light 6. Thistle & Weeds 7. Ghosts That We Knew 8. Awake My Soul 9. Whispers In The Dark 10. Dust Bowl Dance 11. I Will Wait 12. The Cave  English folk rock band captured live in performance at the Red Rocks Ampitheatre in Colorado in summer 2012. As well as footage of the concert itself the journey of the band to Red Rocks is explored, from their humble origins in the West London music scene to their ability to sell out the spectacular 10,000 capacity open-air amphitheatre.",
                        popularity=1.422,
                        poster_path="/gjlSl5SgFtKgTvOyL4kTkuCk5o.jpg",
                        release_date="2012-11-26",
                        title="Mumford & Sons: The Road to Red Rocks",
                        video=False,
                        vote_average=10.0,
                        vote_count=1,
                    ),
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=1421752,
                known_for_department="Acting",
                name="Nikolas Jack Katalaris",
                original_name="Nikolas Jack Katalaris",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[35],
                        id=322316,
                        original_language="en",
                        original_title="Leonard in Slow Motion",
                        overview="Leonard (Martin Starr - 'Freaks &amp; Geeks', 'Knocked Up', and 'Party Down'), exists in slow motion but lives in a regular speed world. When he discovers his office crush is getting transferred to Florida, Leonard decides he must somehow become regular speed to win her heart before she leaves town for good.",
                        popularity=0.6,
                        poster_path=None,
                        release_date="2014-04-06",
                        title="Leonard in Slow Motion",
                        video=False,
                        vote_average=7.0,
                        vote_count=5,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=3964722,
                known_for_department="Acting",
                name="Jack Niedenthal",
                original_name="Jack Niedenthal",
                popularity=0.6,
                profile_path=None,
                known_for=[],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=4035000,
                known_for_department="Acting",
                name="Jack Nieberlain",
                original_name="Jack Nieberlain",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[27, 878],
                        id=219628,
                        original_language="en",
                        original_title="Biohazard: The Alien Force",
                        overview='Triton Indutries has created a genetically-engineered creature using DNA from human sources. During the course of the experiment, however, the host mother carrying the mutant escapes from the laboratory compound, giving birth shortly thereafter. The intellient "baby" beings hunting down and killing its male DNA donors, while at the same time trying to mate with its female donors. The head of the lab wants to destroy the monster before the press can get wind of the story, but the former head of security wants to expose the whole thing.',
                        popularity=0.6,
                        poster_path="/8Erl5terGfetto3Jo74rOh7u7h7.jpg",
                        release_date="1994-09-30",
                        title="Biohazard: The Alien Force",
                        video=False,
                        vote_average=1.8,
                        vote_count=5,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=4042006,
                known_for_department="Camera",
                name="Jack Nielson",
                original_name="Jack Nielson",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/sOuAxEuZoITzD5t1oY2oGhxRwMU.jpg",
                        genre_ids=[],
                        id=1121361,
                        original_language="en",
                        original_title="Things that are Beautiful and Transient",
                        overview="",
                        popularity=0.6,
                        poster_path="/m4BgAJ4LxIxRwEIMYKZPnZkJ5ot.jpg",
                        release_date="",
                        title="Things that are Beautiful and Transient",
                        video=False,
                        vote_average=0.0,
                        vote_count=0,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=4089103,
                known_for_department="Sound",
                name="Jack Nicholson",
                original_name="Jack Nicholson",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/uCqcoeEg53cd7htAa8gtdLbjteR.jpg",
                        genre_ids=[99, 10759],
                        id=227272,
                        original_language="en",
                        original_title=None,
                        overview="Ever wanted to quit your job and go travelling round the world? Well James and Karl did and filmed it all. The backpacking documentary follows James and Karl as they travel through 20 countries in 4 continents over 9 months, covering a distance of over 42,000 miles.  \u200b",
                        popularity=0.6,
                        poster_path="/9xXWinnZlAaErvwTB4tjpBZwYXP.jpg",
                        release_date=None,
                        title=None,
                        video=None,
                        vote_average=10.0,
                        vote_count=3,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=0,
                id=4097703,
                known_for_department="Sound",
                name="Jack Nigh",
                original_name="Jack Nigh",
                popularity=0.6,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/scf5Fgzbr66IFoqaxYwcmrJG0IA.jpg",
                        genre_ids=[37, 12, 28],
                        id=47914,
                        original_language="en",
                        original_title="The White Buffalo",
                        overview="In this strange western version of Moby Dick, Wild Bill Hickok hunts a white buffalo he has seen in a dream. Hickok moves through a variety of uniquely authentic western locations - dim, filthy, makeshift taverns; freezing, slaughterhouse-like frontier towns and beautifully desolate high country - before improbably teaming up with a young Crazy Horse to pursue the creature.",
                        popularity=9.58,
                        poster_path="/szvuG051LtheWv94QBcqldE4Wsu.jpg",
                        release_date="1977-05-01",
                        title="The White Buffalo",
                        video=False,
                        vote_average=5.82,
                        vote_count=100,
                    )
                ],
            ),
            SearchPerson(
                adult=False,
                gender=2,
                id=77763,
                known_for_department="Acting",
                name="Mick Foley",
                original_name="Mick Foley",
                popularity=3.155,
                profile_path="/DHUA9BWpNlue1Wk4eIk2r9zjUF.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/lewYqqt8epnjFhEOIIIINX9Z8EE.jpg",
                        genre_ids=[12, 35, 18],
                        id=463257,
                        original_language="en",
                        original_title="The Peanut Butter Falcon",
                        overview="A down-on-his-luck crab fisherman embarks on a journey to get a young man with Down syndrome to a professional wrestling school in rural North Carolina and away from the retirement home where he’s lived for the past two and a half years.",
                        popularity=14.139,
                        poster_path="/qyQcRGvdW3VtxHR4fSDgPOePEip.jpg",
                        release_date="2019-08-09",
                        title="The Peanut Butter Falcon",
                        video=False,
                        vote_average=7.403,
                        vote_count=1191,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/dxnNEYgTwiX00fzu2J5NtrBWY9y.jpg",
                        genre_ids=[99],
                        id=14271,
                        original_language="en",
                        original_title="Beyond the Mat",
                        overview="Beyond the Mat is a 1999 professional wrestling documentary, directed by Barry W. Blaustein. The movie focuses on the lives of professional wrestlers outside of the ring, especially Mick Foley, Terry Funk, and Jake Roberts. The film heavily focuses on the World Wrestling Federation (WWF), often criticizing it and its chairman Vince McMahon. It also follows Extreme Championship Wrestling, it's rise in popularity, and many other independent wrestlers and organisations.",
                        popularity=4.727,
                        poster_path="/48AfKc79mpRcavpA5Hc7UW9Qqq6.jpg",
                        release_date="1999-10-22",
                        title="Beyond the Mat",
                        video=False,
                        vote_average=7.296,
                        vote_count=76,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/5Ig66JHWuqotsTwtU2P8zg3TJhv.jpg",
                        genre_ids=[99, 18],
                        id=103026,
                        original_language="en",
                        original_title=None,
                        overview="The anticipated WWE Network docuseries will look back on The Undertaker’s storied WWE career and place a focus on the ongoing challenges the wrestling legend appears to have with a career beginning to near it's end.",
                        popularity=7.709,
                        poster_path="/ckKQrIUD9kKAtuTKEkybcajScyA.jpg",
                        release_date=None,
                        title=None,
                        video=None,
                        vote_average=7.4,
                        vote_count=312,
                    ),
                ],
            ),
            SearchPerson(
                adult=False,
                gender=2,
                id=101799,
                known_for_department="Acting",
                name="J.D. Nicholsen",
                original_name="J.D. Nicholsen",
                popularity=0.766,
                profile_path="/38wJ5FrUoC9jgDN402DHYoK1AFU.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/thLAoL6VeZGmCyDpCOeoxLvA8yS.jpg",
                        genre_ids=[10765, 10759],
                        id=76479,
                        original_language="en",
                        original_title=None,
                        overview="A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
                        popularity=353.055,
                        poster_path="/7Ns6tO3aYjppI5bFhyYZurOYGBT.jpg",
                        release_date=None,
                        title=None,
                        video=None,
                        vote_average=8.472,
                        vote_count=8551,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/pysGisnLhmjQB2CGQCAQDxBADsH.jpg",
                        genre_ids=[80, 10765, 18, 9648],
                        id=90462,
                        original_language="en",
                        original_title=None,
                        overview="After a vintage Chucky doll turns up at a suburban yard sale, an idyllic American town is thrown into chaos as a series of horrifying murders begin to expose the town’s hypocrisies and secrets. Meanwhile, the arrival of enemies — and allies — from Chucky’s past threatens to expose the truth behind the killings, as well as the demon doll’s untold origins.",
                        popularity=80.747,
                        poster_path="/kY0BogCM8SkNJ0MNiHB3VTM86Tz.jpg",
                        release_date=None,
                        title=None,
                        video=None,
                        vote_average=7.86,
                        vote_count=3694,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/jjmNCDyeO4yEHAq7DnPXecuw0df.jpg",
                        genre_ids=[10751, 35],
                        id=22081,
                        original_language="en",
                        original_title="Blizzard",
                        overview="A young girl's aunt tells her the tale of a young ice skater and an enchanted reindeer.",
                        popularity=5.759,
                        poster_path="/uLGrJDBi67Bb4e3mMGoH3duefhw.jpg",
                        release_date="2003-05-15",
                        title="Blizzard",
                        video=False,
                        vote_average=5.894,
                        vote_count=66,
                    ),
                ],
            ),
            SearchPerson(
                adult=False,
                gender=2,
                id=99347,
                known_for_department="Acting",
                name="Jack La Rue",
                original_name="Jack La Rue",
                popularity=1.4,
                profile_path="/4vmaW11bjvJVftMLTjDQzdtmEYD.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/ek1883HwUWzFliDaE6FAmJ8XoXi.jpg",
                        genre_ids=[18, 10749, 10752],
                        id=22649,
                        original_language="en",
                        original_title="A Farewell to Arms",
                        overview="A tale of the World War I love affair, begun in Italy, between American ambulance driver Lt. Frederic Henry and British nurse Catherine Barkley. Eventually separated by Frederic's transfer, tremendous challenges and difficult decisions face each as the war rages on.",
                        popularity=6.387,
                        poster_path="/eNmPByGZJqlp60nCZRhsAlVAb3F.jpg",
                        release_date="1932-12-08",
                        title="A Farewell to Arms",
                        video=False,
                        vote_average=6.211,
                        vote_count=116,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/5cS4Es0uCJUs9SrJICojZ4HhuT5.jpg",
                        genre_ids=[80],
                        id=35986,
                        original_language="en",
                        original_title="No Orchids for Miss Blandish",
                        overview="Filmed in England but set in New York, No Orchids For Miss Blandish tells of a sheltered heiress who is abducted on her wedding night by a trio of cheap hoods, in what starts out as a jewel robbery and turns into a kidnapping/murder when one of them kills the bridegroom. More mayhem ensues as the three kidnappers soon end up dead.",
                        popularity=1.585,
                        poster_path="/xB9moW3XkdCZ0lXn3hWVUgAaSJw.jpg",
                        release_date="1948-04-15",
                        title="No Orchids for Miss Blandish",
                        video=False,
                        vote_average=6.053,
                        vote_count=19,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/2eKw8s2m2MZv0fLrmavNDZUS4BE.jpg",
                        genre_ids=[12, 18, 10751],
                        id=16515,
                        original_language="en",
                        original_title="Captains Courageous",
                        overview="Harvey, the arrogant and spoiled son of an indulgent absentee-father, falls overboard from a transatlantic steamship and is rescued by a fishing vessel on the Grand Banks. Harvey fails to persuade them to take him ashore, nor convince the crew of his wealth. The captain offers him a low-paid job, until they return to port, as part of the crew that turns him into a mature, considerate young man.",
                        popularity=7.512,
                        poster_path="/qhJNHLwIcMqDKBwsr9uMDOumO33.jpg",
                        release_date="1937-06-25",
                        title="Captains Courageous",
                        video=False,
                        vote_average=7.369,
                        vote_count=137,
                    ),
                ],
            ),
            SearchPerson(
                adult=False,
                gender=2,
                id=75079,
                known_for_department="Editing",
                name="Nicolas Gaster",
                original_name="Nicolas Gaster",
                popularity=0.748,
                profile_path=None,
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path="/mvUAo9ACgmLpS4Ofc2IwD4n7WCt.jpg",
                        genre_ids=[878, 18],
                        id=17431,
                        original_language="en",
                        original_title="Moon",
                        overview="With only three weeks left in his three year contract, Sam Bell is getting anxious to finally return to Earth. He is the only occupant of a Moon-based manufacturing facility along with his computer and assistant, GERTY. When he has an accident however, he wakens to find that he is not alone.",
                        popularity=16.174,
                        poster_path="/35IU0Mq0zFsN1mYwDGts5mKc77n.jpg",
                        release_date="2009-06-12",
                        title="Moon",
                        video=False,
                        vote_average=7.57,
                        vote_count=5170,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/2K84O2cr0jRH7ROeeHJ3zbTR8Uf.jpg",
                        genre_ids=[18, 35],
                        id=93812,
                        original_language="en",
                        original_title=None,
                        overview="A genre-bending, anti-historical ride through 18th century Russia following the rise of Catherine the Nothing to Catherine the Great and her explosive relationship with husband Peter, the emperor of Russia.",
                        popularity=38.949,
                        poster_path="/tpz9UQ3hUwYufNcKWVW00FCjWyc.jpg",
                        release_date=None,
                        title=None,
                        video=None,
                        vote_average=8.179,
                        vote_count=879,
                    ),
                    SearchMovie(
                        adult=0,
                        backdrop_path="/4ANK5uSBMQxEdHSYqSqs4YMY0Ed.jpg",
                        genre_ids=[18, 10749],
                        id=283227,
                        original_language="en",
                        original_title="A Little Chaos",
                        overview="A landscape gardener is hired by famous architect Le Nôtre to construct the grand gardens at the palace of Versailles. As the two work on the palace, they find themselves drawn to each other and are thrown into rivalries within the court of King Louis XIV.",
                        popularity=8.204,
                        poster_path="/70uwNpUIIVS1AVLpIAgr4EYfD4T.jpg",
                        release_date="2015-03-26",
                        title="A Little Chaos",
                        video=False,
                        vote_average=6.318,
                        vote_count=619,
                    ),
                ],
            ),
            SearchPerson(
                adult=False,
                gender=2,
                id=2902049,
                known_for_department="Acting",
                name="Ulualoaiga Emelio",
                original_name="Ulualoaiga Emelio",
                popularity=0.6,
                profile_path="/jOyXw2YYN2gcqpZkdxOhyypuFpo.jpg",
                known_for=[
                    SearchMovie(
                        adult=0,
                        backdrop_path=None,
                        genre_ids=[28, 18],
                        id=535047,
                        original_language="en",
                        original_title="NWA Battle of the Belts",
                        overview="Name of the event:\tNWA Battle Of The Belts / Date:02.09.1985 / Promotion:Championship Wrestling From Florida, National Wrestling Alliance / Location:\tTampa, Florida, USA/ Arena:The Sundome",
                        popularity=0.65,
                        poster_path=None,
                        release_date="1985-02-09",
                        title="NWA Battle of the Belts",
                        video=True,
                        vote_average=8.0,
                        vote_count=2,
                    )
                ],
            ),
        ],
    ),
]

search_collection_expected = [
    (
        "All Stars Collection",
        [
            SearchCollection(
                adult=False,
                backdrop_path="/g8XTODghMizLlEd9TJ9NsRXaYh0.jpg",
                id=257071,
                name="All Stars Collection",
                original_language="nl",
                original_name="All Stars Collectie",
                overview="",
                poster_path="/823g88J58s4bnhKT4ADXgOFFt62.jpg",
            )
        ],
    ),
    (
        "star",
        [
            SearchCollection(
                adult=False,
                backdrop_path="/g8XTODghMizLlEd9TJ9NsRXaYh0.jpg",
                id=257071,
                name="All Stars Collection",
                original_language="nl",
                original_name="All Stars Collectie",
                overview="",
                poster_path="/823g88J58s4bnhKT4ADXgOFFt62.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/hcP3F4I3Nl80YCwLFcfbPigc3Tq.jpg",
                id=819105,
                name="Shoujo Kageki Revue Starlight Collection",
                original_language="ja",
                original_name="少女☆歌劇 レヴュースタァライトシリーズ",
                overview="",
                poster_path="/ieSE5JmBNyvJxcMKVrdTtTSAirZ.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/kEKeb4D26qSrUVguic7eUPfELg9.jpg",
                id=247559,
                name="New Fist of the North Star",
                original_language="en",
                original_name="新・北斗の拳",
                overview="New Fist of the North Star is a three-episode anime OVA series based on the Fist of the North Star franchise, directed by Takashi Watanabe and produced by OB Planning. The story was adapted from Jubaku no Machi, a 1996 Hokuto no Ken novel written by Buronson and Tetsuo Hara set sometime after the conclusion of the original manga. An English dubbed version of the OVA was produced by ADV Films in 2004.",
                poster_path="/pISoA3SYRG3qvGzZfUDsyfhckiQ.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=623888,
                name="Romancing Star Collection",
                original_language="en",
                original_name="精裝追女仔",
                overview="",
                poster_path="/1EYtpGfnrkwfnJbwif7JhsZwMa1.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/dRn9EOhDWNDJuxSz0WXgxfHbLyn.jpg",
                id=689287,
                name="Re:ZERO -Starting Life in Another World- Collection",
                original_language="en",
                original_name="Re：ゼロから始める異世界生活",
                overview="Natsuki Subaru, an ordinary high school student, is on his way home from the convenience store when he finds himself transported to another world. As he's lost and confused in a new world where he doesn't even know left from right, the only person to reach out to him was a beautiful girl with silver hair. Determined to repay her somehow for saving him from his own despair, Subaru agrees to help the girl find something she's looking for...",
                poster_path="/xcJ3U7sSdI0VVihU9oHxfNZ7umH.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/34NUeUckBhNxd2yhD3FtbxsSDUZ.jpg",
                id=1124485,
                name="Star World Collection",
                original_language="en",
                original_name="Коллекция Звёздный мир",
                overview="Gennady Tishchenko's unfinished science-fiction saga. The stories center around Inspector Yanin and his adventures exploring distant planets and learning about the lives of their strange inhabitants.",
                poster_path=None,
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/qvukxg0eB9kpHVKOBsr1lynoM94.jpg",
                id=114374,
                name="Fist of the North Star: The Legends of the True Savior",
                original_language="it",
                original_name="真救世主伝説 北斗の拳",
                overview="Fist of the North Star: The Legends of the True Savior is a Japanese animated film series produced by TMS Entertainment and North Stars Pictures based on the manga Fist of the North Star written by Buronson and illustrated by Tetsuo Hara. The films are an updated re-imagining of the original story narrated in the manga, including additional detail expanding of the story, modern artwork and animation, new characters, as well as minor alterations to some events. The series spans three theatrical films and two OVAs each focusing on a different set of chapters and main characters from the original story. These were released in Japan during a three year span between 2006 to 2008, culminating with the 25th anniversary of the original manga. The first film, as well as both OVAs, were distributed by Toho. A portion of the project's budget came from a trust fund established by SMBC Friend Securities, which was raised over 23 billion yen.",
                poster_path="/xhknQpIUioANiXbKIMDbD7rOEHy.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=525094,
                name="Drei teuflisch starke Frauen Filmreihe",
                original_language="de",
                original_name="Drei teuflisch starke Frauen Filmreihe",
                overview="",
                poster_path=None,
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=780175,
                name="Amateur Porn Star Killer Collection",
                original_language="en",
                original_name="Amateur Porn Star Killer Collection",
                overview="Amateur Porn Star Killer Collection",
                poster_path=None,
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=786436,
                name="Star of the Giants Collection",
                original_language="en",
                original_name="Star of the Giants Collection",
                overview="The anime film series",
                poster_path=None,
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/bzOeeq73FPTaroAckXijaq9KkMP.jpg",
                id=533603,
                name="Stars 80 Collection",
                original_language="fr",
                original_name="Stars 80 Collection",
                overview="",
                poster_path="/6A9zuMlA1o6iQ8syYUmh3N2yDMN.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=702737,
                name="Morning Star Trilogy",
                original_language="en",
                original_name="Morning Star Trilogy",
                overview="Beny Tchaicovsky's surreal, computer-animated, three film series.",
                poster_path="/A72oEo0bRRPQ0vliRDXQr7Q1YP4.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=974579,
                name="Star of David (Animated) Collection",
                original_language="en",
                original_name="Star of David (Animated) Collection",
                overview="\u200e\u200e\u200f\u200f\u200e \u200e\u200f\u200f\u200e \u200e\u200f\u200f\u200e \u200e\u200f\u200f\u200e \u200e\u200f\u200f\u200e \u200e\u200f\u200f\u200e \u200e\u200f\u200f\u200e \u200e",
                poster_path=None,
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=670241,
                name="Fist of the North Star Digest Collection",
                original_language="en",
                original_name="Fist of the North Star Digest Collection",
                overview="Collection of the Fist of the North Star Digest Movies",
                poster_path="/2E8tc6UaacPoZ0r5AVGI4h1HeC9.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=423877,
                name="Turkish Star Wars",
                original_language="en",
                original_name="Turkish Star Wars",
                overview="Dünyayı Kurtaran Adam (The Man Who Saved the World) and Dünyayi Kurtaran Adam'in Oglu (The Son of the Man who Saved the World) is a series of Turkish adventure films also known as Turkish Star Wars because of its notorious use of unauthorized footage from Star Wars and other movies worked into the film.",
                poster_path=None,
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/1LIggBhNSqYYdjDqYMNR1mcb1n1.jpg",
                id=160136,
                name="Press Start Collection",
                original_language="en",
                original_name="Press Start Collection",
                overview="Average suburban youth Zack Nimbus is recruited by an ill-tempered ninja and a tough-as-nails space soldier to save the world from a tyrannical, but comically insecure, sorcerer.",
                poster_path="/A2YzFEMd3DBSZq9uVXmKZDbasM3.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=206921,
                name="Star Wreck Collection",
                original_language="en",
                original_name="Star Wreck Collection",
                overview="Star Wreck is a series of Finnish Star Trek parody movies started by Samuli Torssonen in 1992. The first movie, simply named Star Wreck, was a simple Star Control-like animation with three ships shooting at each other, but later movies featured 3D CGI, animated characters and, in the latest films, live actors.  Often Star Wreck is used to refer to the latest and most popular film Star Wreck: In the Pirkinning. Star Wreck relates the adventures of James B. Pirk (named after the Star Trek character James T. Kirk), Captain of the starship C.P.P. Potkustartti (English C.P.P. Kickstart). Other characters include Mr. Fukov, Mr. Spook (Finnish: Mr. Spökö), Mr. Dwarf (Wuf), Ensign Shitty and Mr. Info (loosely based, respectively, on Star Trek's Pavel Chekov, Mr. Spock, Worf, Scotty, and Data). The characters speak Finnish, but subtitles in various languages, including Klingon, are available.",
                poster_path=None,
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/an2ceogCMamhYxluJFGcDSedAbu.jpg",
                id=325798,
                name="Star Crash Collection",
                original_language="de",
                original_name="Star Crash Collection",
                overview="",
                poster_path="/6PEV9Wgg5ISfjjSbgmDPFqmEP3u.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/6kilSOTKqyqw1cTfgUak2Y2Gz9O.jpg",
                id=302331,
                name="LEGO Star Wars Collection",
                original_language="en",
                original_name="LEGO Star Wars Collection",
                overview="A set of animated LEGO movies based on the Star Wars universe.",
                poster_path="/sHlgKW5hlQvwJseJkmnkSmL3YDI.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=1034301,
                name="Tajemství staré bambitky (kolekce)",
                original_language="cs",
                original_name="Tajemství staré bambitky (kolekce)",
                overview="",
                poster_path=None,
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/a2hSuCbJkosr7Vn7y8M76OaXDqE.jpg",
                id=970645,
                name="Stargirl Collection",
                original_language="en",
                original_name="Stargirl Collection",
                overview="Walt Disney Picture's Stargirl family film series",
                poster_path="/8Bh8h6jbyT9VGsaljgloHWvY0He.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=632822,
                name="Pup Star Collection",
                original_language="en",
                original_name="Pup Star Collection",
                overview="Welcome to a world where dogs can not only talk — they can SING!",
                poster_path="/pyAaBK5Ynb9MFeSaclTebQvkoIX.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=141748,
                name="Robot Chicken - Star Wars Collection",
                original_language="en",
                original_name="Robot Chicken - Star Wars Collection",
                overview="A series of Robot Chicken TV films parodying the Star Wars films.",
                poster_path="/m6tP4z5IIk8lIsBTpXu5H0B8hO3.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=1082324,
                name="Stars Fell Collection",
                original_language="en",
                original_name="Stars Fell Collection",
                overview="A series of romantic comedies where an agent has a client pretend to be his lover, only to actually fall in love with her.",
                poster_path=None,
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/VXwSW7UGuNScCTy5V5H9pgioir.jpg",
                id=133830,
                name="Star Wars: The Ewok Adventures Collection",
                original_language="en",
                original_name="Star Wars: The Ewok Adventures Collection",
                overview="The Ewok Adventures is a 1984 American made-for-TV film duology based in the Star Wars setting. It was released theatrically in Europe as Caravan of Courage: An Ewok Adventure, and is known by that title today. The film focuses on the struggles of a brother and sister, stranded on the forest moon of Endor, in locating their parents, who have been kidnapped by a monster known as the Gorax. The film is set sometime between the fifth and sixth episodes of the Star Wars saga. It is the first of two spin-off films featuring the Ewoks from Star Wars Episode VI: Return of the Jedi. A sequel to this movie released in 1985. While the sequel's working title was simply Ewoks II, it was released as Ewoks: The Battle for Endor.",
                poster_path="/vSrIbcWQJ3IL0R5DoWLh0c7HMTz.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/cVYUqWzzUSrkLQwb4jlWAkaFCAX.jpg",
                id=1004630,
                name="LEGO Star Wars (Seasonal) Collection",
                original_language="en",
                original_name="LEGO Star Wars (Seasonal) Collection",
                overview="A collection of LEGO Stars Wars seasonal specials released on Disney+.",
                poster_path="/jHITUzB6fZVOYZ13YCqVTS06iyw.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=1111972,
                name="Star Trek: Picard - The IMAX Live Series Finale Event",
                original_language="en",
                original_name="Star Trek: Picard - The IMAX Live Series Finale Event",
                overview='Get ready to send off Jean-Luc Picard and his crew in style! On Wednesday, April 19, experience the last two episodes of Star Trek: Picard in IMAX, followed by a live-streamed Q&A with the cast of the show.  In the epic, thrilling conclusion of "Star Trek: Picard," a desperate message from a long-lost friend draws Starfleet legend Admiral Jean-Luc Picard into the most daring mission of his life, forcing him to recruit allies spanning generations old and new. This final adventure sets him on a collision course with the legacy of his past and explosive, new revelations that will alter the fate of the Federation forever.',
                poster_path="/lTUzyESRHV7MjMqepQPjkK2yqga.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/fyItL7RXmTRbIaIWPke7Dqfqrqk.jpg",
                id=958299,
                name="Revue Starlight ―The LIVE Collection―",
                original_language="en",
                original_name="Revue Starlight ―The LIVE Collection―",
                overview="Collection of the play version of Revue Starling.",
                poster_path="/eCqvyCzriT5z64bPlLjbgrr3n4x.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/c1Yf8AtAAobnWlrlrE6KpGhOIl4.jpg",
                id=300431,
                name="Lucky Stars Collection",
                original_language="es",
                original_name="Lucky Stars Collection",
                overview="Lucky Stars (or Five Lucky Stars; (Chinese: 福星系列、五福星) was a Hong Kong action comedy film series in the 1980s and 1990s, blending Chinese martial arts with bawdy comedy. The films featured an ensemble cast, with many of the actors appearing in successive films.  The characters of the Five Lucky Stars were originally petty criminals recently out of prison, who started their own cleaning company. By the second film, the cleaning company idea was discarded, and the bumbling gang were instead employed to assist the police.",
                poster_path="/4JaAnOKwbVYXecpn8SkbOnwa5hg.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/gWl5pN2FplE709aVtA4lakwsE6t.jpg",
                id=115575,
                name="Star Trek: Alternate Reality Collection",
                original_language="en",
                original_name="Star Trek: Alternate Reality Collection",
                overview='J.J. Abrams\' cinematic re-envisioning of the Star Trek universe portrayed by a new cast, and set in an alternate reality from earlier films and series (referred to as the "Kelvin" timeline).',
                poster_path="/w2IVqa43Ge49mrY3qSaJWpyDtz6.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/fwVVh9o0WZsZNstpX3O55ff7Hs8.jpg",
                id=44215,
                name="Stargate SG-1 Collection",
                original_language="en",
                original_name="Stargate SG-1 Collection",
                overview="The continuing missions of SG1 and friends as they explore the galaxy using ancient technologies and alien hardware.",
                poster_path="/1iT2nShFRSBsdT71a1MUsyPpoTL.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=1138664,
                name="Starquest Collection",
                original_language="en",
                original_name="Starquest Collection",
                overview="Terminal Voyage AKA Starquest and the quasi-sequel, Starquest II",
                poster_path="/rxAXeW4tYSWvCJeZZ4rAIt3w8EW.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/iKbdiRzFaQaKMtYoeQIuwGoDvSv.jpg",
                id=10522,
                name="Starship Troopers Collection",
                original_language="en",
                original_name="Starship Troopers Collection",
                overview="Starship Troopers is an American military science fiction media franchise based on the 1959 novel of the same name by Robert A. Heinlein and the satirical 1997 film adaptation by screenwriter Edward Neumeier and director Paul Verhoeven.",
                poster_path="/uumu3Xj1ME1632SCsyVJwITgOKZ.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/r7MMQenUURHhAVHFymtOb8AX4Bm.jpg",
                id=115570,
                name="Star Trek: The Next Generation Collection",
                original_language="en",
                original_name="Star Trek: The Next Generation Collection",
                overview="Star Trek: The Next Generation Motion Picture Collection contains the four Next Generation films.",
                poster_path="/jYtNUfMbU6DBbmd4LUS19u4hF4p.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/9BQj9hq0aK6yM9Tm2NJ28jg572y.jpg",
                id=151,
                name="Star Trek: The Original Series Collection",
                original_language="en",
                original_name="Star Trek: The Original Series Collection",
                overview="Star Trek: Original Motion Picture Collection contains the first six Original Series films starring the U.S.S. Enterprise's cast and crew from the 1960s TV series of the same name.",
                poster_path="/vNrbrsHOpXS3whk9DLuBNcjJy1s.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/d8duYyyC9J5T825Hg7grmaabfxQ.jpg",
                id=10,
                name="Star Wars Collection",
                original_language="en",
                original_name="Star Wars Collection",
                overview='An epic space-opera theatrical film series, which depicts the adventures of various characters "a long time ago in a galaxy far, far away…."',
                poster_path="/r8Ph5MYXL04Qzu4QBbq2KjqwtkQ.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/lcXu4fxsrLZOzuwUXYKdHtlauBP.jpg",
                id=363966,
                name="Care Bears Collection",
                original_language="de",
                original_name="Care Bears Collection",
                overview="Collection of Classic Care Bears movies from the 80s through the late 90s",
                poster_path="/zsZ9BkSg0ce9PDcRIGTVFdxMiZs.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path=None,
                id=460845,
                name="Space Battleship Yamato 2199 Collection",
                original_language="ja",
                original_name="Space Battleship Yamato 2199 Collection",
                overview="",
                poster_path="/93beuADTvvLsjjrb0j0zoT29VSe.jpg",
            ),
            SearchCollection(
                adult=False,
                backdrop_path="/i7aSKKP2C2qH53k3L7Wgm7yYZUt.jpg",
                id=501772,
                name="The 100-Year Old Man Collection",
                original_language="no",
                original_name="Hundraåringen Collection",
                overview="The two strange stories of Alan Karlssons life through 100 years of history.",
                poster_path="/pltGbYWNvCUw0G018k7byKNJyWE.jpg",
            ),
        ],
    ),
]
